export enum ECurrency {
  UAH = 'uah',
  USD = 'usd',
  EUR = 'eur',
  AUD = 'aud',
  CAD = 'cad',
  CZK = 'czk',
  DKK = 'dkk',
  HUF = 'huf',
  ILS = 'ils',
  JPY = 'jpy',
  LVL = 'lvl',
  LTL = 'ltl',
  NOK = 'nok',
  SKK = 'skk',
  SEK = 'sek',
  CHF = 'chf',
  GBP = 'gbp',
  BYR = 'byr',
  GEL = 'gel',
  PLZ = 'plz',
}
