export enum ECurrency {
  UAH = 'UAH',
  USD = 'USD',
  EUR = 'EUR',
  AUD = 'AUD',
  CAD = 'CAD',
  CZK = 'CZK',
  DKK = 'DKK',
  HUF = 'HUF',
  ILS = 'ILS',
  JPY = 'JPY',
  LVL = 'LVL',
  LTL = 'LTL',
  NOK = 'NOK',
  SKK = 'SKK',
  SEK = 'SEK',
  CHF = 'CHF',
  GBP = 'GBP',
  BYR = 'BYR',
  GEL = 'GEL',
  PLZ = 'PLZ',
}
